### ISSUE TITLE
Changing Gazebo Physics

### ISSUE THREAD

**Issue by HB-Liang** [chvmp/champ#107] opened 2022-11-15 12:58 UTC
Hi there, recently I keep moving on quadruped and solve that annoying initial position problem.
I come up with another problem that I need a quadruped working with a drone in a same gazebo world.
But they are not compatible as my drone works fine in the world physics with max_time_step=0.004 and real_time_update_rate=250.
In the same world, I use spawn_robot.launch in champ_config as a default spawning.
And here is what it behaves:
![sample 00_00_00-00_00_30~1](https://user-images.githubusercontent.com/114042103/201924780-c74ef132-9503-40cd-a58a-4766b4d9cfcc.gif)
Would you please give some advise on changing quadruped setup?
BTW, quadruped works fine in a world with physics max_time_step=0.001 and real_time_update_rate=1000, but drone doesn't.
Thanks.

**Comment by grassjelly** [comment] 2022-11-16 10:20
I’m afraid you can’t run 2 different physics parameters in a single Gazebo world. You might need to decide which robot to adapt to another

**Comment by HB-Liang** [comment] 2022-11-16 10:24
That's the point, would you please give me some advise on adjusting quadruped's parameter to run in world with 0.004&250?

**Comment by RamCharanThota** [comment] 2022-11-18 05:39
Hi @HB-Liang, I am not sure this answer might help you to solve your issue. I had same issues with robot  jumping around. For me, it is mainly due to PID values in the controls configuration values of the robot. I have tuned them until stabilising the robot at start. Hopefully, it will resolve your issue.

**Comment by grassjelly** [comment] 2022-11-29 18:37
closing this as the issue is more Gazebo related. Feel free to re-open this

**Closed by grassjelly** 2022-11-29 18:37 UTC
